inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]
data:
  translation: 0
  input_folder: /mnt/data/dataset/Replica/vmap/office_2/imap/00
  output: output/Replica/office2