inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.4,5.5],[-2.5,4.4],[-1.4,1.8]]
  marching_cubes_bound: [[-1.3,5.4],[-2.4,4.3],[-1.3,1.7]]
data:
  translation: 0
  input_folder: /mnt/data/dataset/Replica/vmap/office_4/imap/00
  output: output/Replica/office4