inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]
data:
  translation: 0
  input_folder: /mnt/data/dataset/Replica/vmap/room_2/imap/00
  output: output/Replica/room2